import Clear.ReasoningPrinciple

import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.checked_sub_uint256
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.Common.if_4451958921457272093
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.abi_encode_uint256_uint256
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.Common.block_1492471849597063814
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.storage_array_index_access_bytes32_dyn__dyn_5278
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.storage_array_index_access_bytes32_dyn__dyn
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.update_storage_value_bytes32_to_bytes32
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.Common.block_5752024616743232143
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.Common.for_4939860823883042599
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.mod_uint256
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.extract_from_storage_value_dynamict_bytes32
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.fun_efficientHash
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.checked_add_uint256
import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.checked_div_uint256

import generated.L2InteropCommitmentTree.L2InteropCommitmentTree.fun_updateLeaf_5202_gen


namespace generated.L2InteropCommitmentTree.L2InteropCommitmentTree

section

open Clear EVMState Ast Expr Stmt FunctionDefinition State Interpreter ExecLemmas OutOfFuelLemmas Abstraction YulNotation PrimOps ReasoningPrinciple Utilities L2InteropCommitmentTree.Common generated.L2InteropCommitmentTree L2InteropCommitmentTree

def A_fun_updateLeaf_5202 (var : Identifier) (var_index var_itemHash : Literal) (s₀ s₉ : State) : Prop := fun_updateLeaf_5202_concrete_of_code.1 var var_index var_itemHash s₀ s₉

lemma fun_updateLeaf_5202_abs_of_concrete {s₀ s₉ : State} {var var_index var_itemHash} :
  Spec (fun_updateLeaf_5202_concrete_of_code.1 var var_index var_itemHash) s₀ s₉ →
  Spec (A_fun_updateLeaf_5202 var var_index var_itemHash) s₀ s₉ := by
  intro h
  simpa [A_fun_updateLeaf_5202] using h

end

end generated.L2InteropCommitmentTree.L2InteropCommitmentTree
