import Clear.ReasoningPrinciple

import generated.AtomicFlowManager.AtomicFlowManager.read_from_calldatat_bool
import generated.AtomicFlowManager.AtomicFlowManager.Common.switch_1103755726224842072
import generated.AtomicFlowManager.AtomicFlowManager.fun_authenticateRoot
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_7931362525754756608
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_uint256_uint256_7838
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_470174221163834814
import generated.AtomicFlowManager.AtomicFlowManager.constant_L2_INTEROP_ROOT_STORAGE_ADDR
import generated.AtomicFlowManager.AtomicFlowManager.cleanup_address
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_5098520325777672981
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_uint256_uint256
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_3511639205281197695
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_7069222774777857031
import generated.AtomicFlowManager.AtomicFlowManager.revert_forward
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_6625194476214591809
import generated.AtomicFlowManager.AtomicFlowManager.finalize_allocation
import generated.AtomicFlowManager.AtomicFlowManager.abi_decode_struct_StoredInteropRoot_fromMemory
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_815393075437808839
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_3887242433341914094
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_uint256_uint64
import generated.AtomicFlowManager.AtomicFlowManager.Common.switch_7641392040944949440
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_bool_uint256_uint64_7917
import generated.AtomicFlowManager.AtomicFlowManager.access_calldata_tail_array_bytes32_dyn_calldata
import generated.AtomicFlowManager.AtomicFlowManager.fun_readAggregationHopPath
import generated.AtomicFlowManager.AtomicFlowManager.fun_verifyLastBatchInRoot
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_bool_uint256_uint64
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_5310774309651988512
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_5184646599768247819
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_1471456103019789360
import generated.AtomicFlowManager.AtomicFlowManager.abi_decode_struct_IMTLeaf
import generated.AtomicFlowManager.AtomicFlowManager.abi_decode_available_length_array_bytes32_dyn
import generated.AtomicFlowManager.AtomicFlowManager.fun_verifyNonInclusion
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_5583277985193582718
import generated.AtomicFlowManager.AtomicFlowManager.cleanup_bool

import generated.AtomicFlowManager.AtomicFlowManager.fun_verifyTimeoutAbsence_gen


namespace generated.AtomicFlowManager.AtomicFlowManager

section

open Clear EVMState Ast Expr Stmt FunctionDefinition State Interpreter ExecLemmas OutOfFuelLemmas Abstraction YulNotation PrimOps ReasoningPrinciple Utilities AtomicFlowManager.Common generated.AtomicFlowManager AtomicFlowManager

def A_fun_verifyTimeoutAbsence  (var__absence_offset var__commitValue var_deadline var__expectedSlChainId : Literal) (s₀ s₉ : State) : Prop := sorry

lemma fun_verifyTimeoutAbsence_abs_of_concrete {s₀ s₉ : State} { var__absence_offset var__commitValue var_deadline var__expectedSlChainId} :
  Spec (fun_verifyTimeoutAbsence_concrete_of_code.1  var__absence_offset var__commitValue var_deadline var__expectedSlChainId) s₀ s₉ →
  Spec (A_fun_verifyTimeoutAbsence  var__absence_offset var__commitValue var_deadline var__expectedSlChainId) s₀ s₉ := by
  unfold fun_verifyTimeoutAbsence_concrete_of_code A_fun_verifyTimeoutAbsence
  sorry

end

end generated.AtomicFlowManager.AtomicFlowManager
