import Clear.ReasoningPrinciple

import generated.AtomicFlowManager.AtomicFlowManager.fun_authenticateRoot
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_4038532911225750954
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_uint256_uint256_7396
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_2718655335929809541
import generated.AtomicFlowManager.AtomicFlowManager.abi_encode_uint256_uint64
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_4452153148412905320
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_2417317032816978091
import generated.AtomicFlowManager.AtomicFlowManager.access_calldata_tail_array_uint256_dyn_calldata
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_796372381056767535
import generated.AtomicFlowManager.AtomicFlowManager.abi_decode_struct_IMTLeaf
import generated.AtomicFlowManager.AtomicFlowManager.abi_decode_available_length_array_bytes32_dyn
import generated.AtomicFlowManager.AtomicFlowManager.fun_verifyNonInclusion
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_6276723684304531529
import generated.AtomicFlowManager.AtomicFlowManager.cleanup_bool
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_8389339499570140962
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_4570946156660602702
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_1514038983519215954
import generated.AtomicFlowManager.AtomicFlowManager.Common.block_1095663342937573923
import generated.AtomicFlowManager.AtomicFlowManager.checked_add_uint256_7469
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_7496580940294017731
import generated.AtomicFlowManager.AtomicFlowManager.Common.if_3231606368080476909

import generated.AtomicFlowManager.AtomicFlowManager.fun_verifyTimeoutAdjacency_gen


namespace generated.AtomicFlowManager.AtomicFlowManager

section

open Clear EVMState Ast Expr Stmt FunctionDefinition State Interpreter ExecLemmas OutOfFuelLemmas Abstraction YulNotation PrimOps ReasoningPrinciple Utilities AtomicFlowManager.Common generated.AtomicFlowManager AtomicFlowManager

def A_fun_verifyTimeoutAdjacency  (var_absence_offset var_successor_offset var__commitValue var__deadline var_expectedSlChainId : Literal) (s₀ s₉ : State) : Prop := fun_verifyTimeoutAdjacency_concrete_of_code.1  var_absence_offset var_successor_offset var__commitValue var__deadline var_expectedSlChainId s₀ s₉

lemma fun_verifyTimeoutAdjacency_abs_of_concrete {s₀ s₉ : State} { var_absence_offset var_successor_offset var__commitValue var__deadline var_expectedSlChainId} :
  Spec (fun_verifyTimeoutAdjacency_concrete_of_code.1  var_absence_offset var_successor_offset var__commitValue var__deadline var_expectedSlChainId) s₀ s₉ →
  Spec (A_fun_verifyTimeoutAdjacency  var_absence_offset var_successor_offset var__commitValue var__deadline var_expectedSlChainId) s₀ s₉ := by
  intro h
  simpa [A_fun_verifyTimeoutAdjacency] using h

end

end generated.AtomicFlowManager.AtomicFlowManager
