#!/usr/bin/env bash
# Generate INDEX.md for a contract's generated Lean files
# Usage: ./scripts/generate-index.sh <contract-name>
# Example: ./scripts/generate-index.sh L1Nullifier

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"

if [ $# -lt 1 ]; then
    echo "Usage: $0 <contract-name>"
    exit 1
fi

CONTRACT="$1"
GEN_DIR="$ROOT_DIR/generated/$CONTRACT/$CONTRACT"
COMMON_DIR="$GEN_DIR/Common"
INDEX="$ROOT_DIR/generated/$CONTRACT/INDEX.md"

if [ ! -d "$GEN_DIR" ]; then
    echo "Error: $GEN_DIR not found"
    exit 1
fi

# Extract imports from a _gen.lean file (module names relative to contract)
# Returns e.g. "finalize_allocation", "Common.if_123456"
get_imports() {
    local file="$1"
    grep '^import generated\.' "$file" 2>/dev/null \
        | sed 's/import generated\.[^.]*\.[^.]*\.//' \
        | sed 's/_gen$//' \
        | sed 's/_user$//' \
        | sort -u
}

{
echo "# $CONTRACT Function Index"
echo ""
echo "Auto-generated by \`scripts/generate-index.sh\`."
echo ""

# --- Solidity Functions (fun_*) ---
echo "## Solidity Functions"
echo ""
for gen_file in "$GEN_DIR"/fun_*_gen.lean; do
    [ -f "$gen_file" ] || continue
    fname=$(basename "$gen_file" _gen.lean)
    imports=$(get_imports "$gen_file")

    func_deps=""
    common_deps=""
    helper_deps=""

    while IFS= read -r imp; do
        [ -z "$imp" ] && continue
        case "$imp" in
            Common.if_*|Common.for_*|Common.switch_*)
                common_deps="$common_deps  - \`$imp\`\n" ;;
            fun_*|modifier_*|external_fun_*)
                func_deps="$func_deps  - \`$imp\`\n" ;;
            *)
                helper_deps="$helper_deps  - \`$imp\`\n" ;;
        esac
    done <<< "$imports"

    echo "### \`$fname\`"
    if [ -n "$func_deps" ]; then
        echo "- **Calls:**"
        echo -e "$func_deps"
    fi
    if [ -n "$helper_deps" ]; then
        echo "- **Helpers:**"
        echo -e "$helper_deps"
    fi
    if [ -n "$common_deps" ]; then
        echo "- **Control flow:**"
        echo -e "$common_deps"
    fi
    if [ -z "$func_deps" ] && [ -z "$helper_deps" ] && [ -z "$common_deps" ]; then
        echo "- *(leaf function — no dependencies)*"
    fi
    echo ""
done

# --- Modifiers ---
has_modifiers=false
for gen_file in "$GEN_DIR"/modifier_*_gen.lean; do
    [ -f "$gen_file" ] || continue
    has_modifiers=true
    break
done
if $has_modifiers; then
    echo "## Modifiers"
    echo ""
    for gen_file in "$GEN_DIR"/modifier_*_gen.lean; do
        [ -f "$gen_file" ] || continue
        fname=$(basename "$gen_file" _gen.lean)
        imports=$(get_imports "$gen_file")
        echo "### \`$fname\`"
        if [ -n "$imports" ]; then
            echo "- **Dependencies:**"
            while IFS= read -r imp; do
                [ -z "$imp" ] && continue
                echo "  - \`$imp\`"
            done <<< "$imports"
        fi
        echo ""
    done
fi

# --- External Dispatch ---
has_external=false
for gen_file in "$GEN_DIR"/external_fun_*_gen.lean; do
    [ -f "$gen_file" ] || continue
    has_external=true
    break
done
if $has_external; then
    echo "## External Dispatch"
    echo ""
    for gen_file in "$GEN_DIR"/external_fun_*_gen.lean; do
        [ -f "$gen_file" ] || continue
        fname=$(basename "$gen_file" _gen.lean)
        imports=$(get_imports "$gen_file")
        echo "- \`$fname\`"
        while IFS= read -r imp; do
            [ -z "$imp" ] && continue
            echo "  - → \`$imp\`"
        done <<< "$imports"
    done
    echo ""
fi

# --- ABI Encoding ---
echo "## ABI Encoding"
echo ""
for gen_file in "$GEN_DIR"/abi_encode_*_gen.lean; do
    [ -f "$gen_file" ] || continue
    fname=$(basename "$gen_file" _gen.lean)
    echo "- \`$fname\`"
done
echo ""

# --- ABI Decoding ---
echo "## ABI Decoding"
echo ""
for gen_file in "$GEN_DIR"/abi_decode_*_gen.lean; do
    [ -f "$gen_file" ] || continue
    fname=$(basename "$gen_file" _gen.lean)
    echo "- \`$fname\`"
done
echo ""

# --- Storage/Memory ---
echo "## Storage & Memory"
echo ""
for gen_file in "$GEN_DIR"/*_gen.lean; do
    [ -f "$gen_file" ] || continue
    fname=$(basename "$gen_file" _gen.lean)
    case "$fname" in
        mapping_index_*|read_from_*|update_storage_*|extract_from_*|allocate_*|finalize_*|write_to_*)
            echo "- \`$fname\`" ;;
    esac
done
echo ""

# --- Utilities ---
echo "## Utilities"
echo ""
for gen_file in "$GEN_DIR"/*_gen.lean; do
    [ -f "$gen_file" ] || continue
    fname=$(basename "$gen_file" _gen.lean)
    case "$fname" in
        cleanup_*|validator_*|panic_error_*|require_helper_*|checked_*|constant_*)
            echo "- \`$fname\`" ;;
        fun_*|modifier_*|external_fun_*|abi_encode_*|abi_decode_*) ;;
        mapping_index_*|read_from_*|update_storage_*|extract_from_*|allocate_*|finalize_*|write_to_*) ;;
        *)
            echo "- \`$fname\`" ;;
    esac
done
echo ""

# --- Common/ Control Flow Blocks ---
if [ -d "$COMMON_DIR" ]; then
    echo "## Common/ Control Flow Blocks"
    echo ""

    # Build reverse map: common block → which functions use it
    # Write to temp file: "block_name parent_name" per line
    TMPMAP=$(mktemp)
    for gen_file in "$GEN_DIR"/*_gen.lean; do
        [ -f "$gen_file" ] || continue
        parent=$(basename "$gen_file" _gen.lean)
        while IFS= read -r imp; do
            [ -z "$imp" ] && continue
            case "$imp" in
                Common.*)
                    block=$(echo "$imp" | sed 's/^Common\.//')
                    echo "$block $parent" >> "$TMPMAP"
                    ;;
            esac
        done <<< "$(get_imports "$gen_file")"
    done

    # Helper to look up parents for a block
    get_parents() {
        local block="$1"
        grep "^$block " "$TMPMAP" 2>/dev/null | awk '{print $2}' | paste -sd ', ' -
    }

    # List if blocks
    if_count=$(ls "$COMMON_DIR"/if_*_gen.lean 2>/dev/null | wc -l | tr -d ' ')
    echo "### if blocks ($if_count)"
    echo ""
    for f in "$COMMON_DIR"/if_*_gen.lean; do
        [ -f "$f" ] || continue
        block=$(basename "$f" _gen.lean)
        used_by=$(get_parents "$block")
        echo "- \`$block\` — used by: ${used_by:-unknown}"
    done
    echo ""

    # List for blocks
    for_count=$(ls "$COMMON_DIR"/for_*_gen.lean 2>/dev/null | wc -l | tr -d ' ')
    if [ "$for_count" -gt 0 ]; then
        echo "### for blocks ($for_count)"
        echo ""
        for f in "$COMMON_DIR"/for_*_gen.lean; do
            [ -f "$f" ] || continue
            block=$(basename "$f" _gen.lean)
            used_by=$(get_parents "$block")
            echo "- \`$block\` — used by: ${used_by:-unknown}"
        done
        echo ""
    fi

    # List switch blocks
    switch_count=$(ls "$COMMON_DIR"/switch_*_gen.lean 2>/dev/null | wc -l | tr -d ' ')
    if [ "$switch_count" -gt 0 ]; then
        echo "### switch blocks ($switch_count)"
        echo ""
        for f in "$COMMON_DIR"/switch_*_gen.lean; do
            [ -f "$f" ] || continue
            block=$(basename "$f" _gen.lean)
            used_by=$(get_parents "$block")
            echo "- \`$block\` — used by: ${used_by:-unknown}"
        done
        echo ""
    fi

    rm -f "$TMPMAP"
fi

} > "$INDEX"

echo "Generated $INDEX"
echo "$(wc -l < "$INDEX" | tr -d ' ') lines"
