import Clear.ReasoningPrinciple

import generated.L2AssetRouter.L2AssetRouter.Common.if_1971690744533170850
import generated.L2AssetRouter.L2AssetRouter.Common.if_1068904302988658311
import generated.L2AssetRouter.L2AssetRouter.panic_error_0x32
import generated.L2AssetRouter.L2AssetRouter.Common.if_5744837567160025334
import generated.L2AssetRouter.L2AssetRouter.Common.if_338934344282501580
import generated.L2AssetRouter.L2AssetRouter.Common.if_5287788961942107784
import generated.L2AssetRouter.L2AssetRouter.Common.if_3680740834951988335
import generated.L2AssetRouter.L2AssetRouter.abi_decode_bytes

import generated.L2AssetRouter.L2AssetRouter.fun_decodeAssetRouterBridgehubDepositData_gen


namespace generated.L2AssetRouter.L2AssetRouter

section

open Clear EVMState Ast Expr Stmt FunctionDefinition State Interpreter ExecLemmas OutOfFuelLemmas Abstraction YulNotation PrimOps ReasoningPrinciple Utilities L2AssetRouter.Common generated.L2AssetRouter L2AssetRouter

def A_fun_decodeAssetRouterBridgehubDepositData (var_assetId var_transferData_mpos : Identifier) (var_dataWithVersion_offset var_dataWithVersion_length : Literal) (s₀ s₉ : State) : Prop := fun_decodeAssetRouterBridgehubDepositData_concrete_of_code.1 var_assetId var_transferData_mpos var_dataWithVersion_offset var_dataWithVersion_length s₀ s₉

lemma fun_decodeAssetRouterBridgehubDepositData_abs_of_concrete {s₀ s₉ : State} {var_assetId var_transferData_mpos var_dataWithVersion_offset var_dataWithVersion_length} :
  Spec (fun_decodeAssetRouterBridgehubDepositData_concrete_of_code.1 var_assetId var_transferData_mpos var_dataWithVersion_offset var_dataWithVersion_length) s₀ s₉ →
  Spec (A_fun_decodeAssetRouterBridgehubDepositData var_assetId var_transferData_mpos var_dataWithVersion_offset var_dataWithVersion_length) s₀ s₉ := by
  intro h
  simpa [A_fun_decodeAssetRouterBridgehubDepositData] using h

end

end generated.L2AssetRouter.L2AssetRouter
